# Generated by Django 5.2.12 on 2026-04-06 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, choices=[('SCD', 'School of Community Dev. & Social Work'), ('SBS', 'School of Business Studies'), ('SHT', 'School of Hospitality & Tourism'), ('SBF', 'School of Beauty & Fashion'), ('SEE', 'School of Electrical Engineering'), ('SCI', 'School of Computing & IT'), ('SHS', 'School of Health Sciences')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, default='students/default.png', null=True, upload_to='students/'),
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_code', models.CharField(max_length=20)),
                ('marks', models.PositiveIntegerField()),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('semester', models.CharField(default='Semester 1 2026', max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField()),
                ('reference_code', models.CharField(help_text='e.g. M-Pesa Transaction ID', max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
