# Generated by Django 5.2.12 on 2026-04-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_student_course_student_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='reference_code',
            field=models.CharField(max_length=50),
        ),
    ]
