# Generated by Django 5.2.12 on 2026-04-13 02:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_feepayment_reference_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresult',
            old_name='unit_name',
            new_name='subject_name',
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examresult',
            name='year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='method',
            field=models.CharField(choices=[('MPESA', 'M-Pesa'), ('CASH', 'Bank/Cash')], default='MPESA', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examresult',
            name='semester',
            field=models.CharField(choices=[('Sem 1', 'Semester 1'), ('Sem 2', 'Semester 2'), ('Sem 3', 'Semester 3')], default='Sem 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='reference_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
