# Generated by Django 5.2.12 on 2026-04-16 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_rename_unit_name_examresult_subject_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffUser',
            fields=[
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': '2. Staff & Lecturers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.student',),
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': '1. Students',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.student',),
        ),
        migrations.AddField(
            model_name='announcement',
            name='audience',
            field=models.CharField(choices=[('ALL', 'Everyone'), ('STUDENTS', 'Students Only'), ('STAFF', 'Staff Only')], default='ALL', max_length=15),
        ),
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examresult',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True, default='All'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='entered_by',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examresult',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
