# Generated by Django 5.2.12 on 2026-04-16 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_staffuser_studentuser_announcement_audience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='announcement',
            table='portal_announcement',
        ),
    ]
