# Generated by Django 5.2.12 on 2026-04-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_announcement_author_alter_announcement_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='classification',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('Sem 1', 'Semester 1'), ('Sem 2', 'Semester 2'), ('Sem 3', 'Semester 3')], default='Sem 1', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, default='students/lec.png', null=True, upload_to='students/'),
        ),
    ]
