# Generated by Django 5.2.12 on 2026-04-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_examresult_classification_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
