# Generated by Django 5.2.12 on 2026-04-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_examresult_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='duration_months',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='student',
            name='expected_graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='official_transcript_status',
            field=models.CharField(choices=[('DRAFT', 'Ongoing / Draft'), ('PENDING', 'Request Pending'), ('ISSUED', 'Officially Issued')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='session_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='session_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='session_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
