# Generated by Django 5.2.12 on 2026-04-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_student_duration_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees_per_semester',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='total_semesters',
            field=models.PositiveIntegerField(default=1, help_text='Total semesters for the full course'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='semester',
            field=models.CharField(choices=[('Sem 1', 'Semester 1'), ('Sem 2', 'Semester 2'), ('Sem 3', 'Semester 3'), ('Sem 4', 'Semester 4'), ('Sem 5', 'Semester 5'), ('Sem 6', 'Semester 6')], default='Sem 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('Sem 1', 'Semester 1'), ('Sem 2', 'Semester 2'), ('Sem 3', 'Semester 3'), ('Sem 4', 'Semester 4'), ('Sem 5', 'Semester 5'), ('Sem 6', 'Semester 6')], default='Sem 1', max_length=10),
        ),
    ]
