# Generated by Django 5.2.12 on 2026-04-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_student_fees_per_semester_student_total_semesters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fee_balance',
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_semesters',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
